/**
 * API Route: Project Management
 * GET - List all projects
 * POST - Create new project
 */

import { NextRequest, NextResponse } from 'next/server';
import prisma from '@/lib/prisma';

export const dynamic = 'force-dynamic';

/**
 * GET /api/admin/projects
 * List all projects with stats
 */
export async function GET(request: NextRequest) {
  try {
    const projects = await prisma.project.findMany({
      include: {
        botAccount: {
          select: {
            username: true,
            isConnected: true,
          },
        },
        _count: {
          select: {
            validCodes: true,
            qrCodes: true,
            deliveries: true,
            tweets: true,
          },
        },
      },
      orderBy: {
        createdAt: 'desc',
      },
    });

    // Get additional stats for each project
    const projectsWithStats = await Promise.all(
      projects.map(async (project) => {
        const [claimedDeliveries, eligibleTweets] = await Promise.all([
          prisma.delivery.count({
            where: {
              projectId: project.id,
              claimed: true,
            },
          }),
          prisma.tweet.count({
            where: {
              projectId: project.id,
              isEligible: true,
            },
          }),
        ]);

        return {
          id: project.id,
          name: project.name,
          poapEventId: project.poapEventId,
          twitterHashtag: project.twitterHashtag,
          isActive: project.isActive,
          botAccount: project.botAccount,
          stats: {
            validCodes: project._count.validCodes,
            qrCodes: project._count.qrCodes,
            deliveries: project._count.deliveries,
            claimedDeliveries,
            tweets: project._count.tweets,
            eligibleTweets,
          },
          createdAt: project.createdAt.toISOString(),
          updatedAt: project.updatedAt.toISOString(),
        };
      })
    );

    return NextResponse.json({
      success: true,
      projects: projectsWithStats,
    });
  } catch (error) {
    console.error('Error fetching projects:', error);
    return NextResponse.json(
      {
        error: 'Failed to fetch projects',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}

/**
 * POST /api/admin/projects
 * Create new project
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();

    const {
      poapEventId,
      poapEditCode,
      allowMultipleClaims = false,
      botReplyEligible,
      botReplyNotEligible,
      botReplyAlreadyClaimed,
      twitterHashtag,
      qrPageTweetTemplate,
      isActive = false, // Default to inactive until configured
      botAccountId,
    } = body;

    // Generate automatic project name with format: Project dd/mm/yyyy hh:mm
    const now = new Date();
    const day = String(now.getDate()).padStart(2, '0');
    const month = String(now.getMonth() + 1).padStart(2, '0');
    const year = now.getFullYear();
    const hours = String(now.getHours()).padStart(2, '0');
    const minutes = String(now.getMinutes()).padStart(2, '0');
    const autoGeneratedName = `Project ${day}/${month}/${year} ${hours}:${minutes}`;

    // Create project with all fields optional
    // Note: If fields are undefined, Prisma will use the @default values from schema.prisma
    const project = await prisma.project.create({
      data: {
        name: autoGeneratedName,
        poapEventId: poapEventId || '',
        poapEditCode: poapEditCode || '',
        allowMultipleClaims,
        // Use schema defaults if not provided
        ...(botReplyEligible && { botReplyEligible }),
        ...(botReplyNotEligible && { botReplyNotEligible }),
        ...(botReplyAlreadyClaimed && { botReplyAlreadyClaimed }),
        ...(twitterHashtag && { twitterHashtag }),
        ...(qrPageTweetTemplate && { qrPageTweetTemplate }),
        isActive,
        botAccountId: botAccountId || null,
      },
      include: {
        botAccount: {
          select: {
            username: true,
            isConnected: true,
          },
        },
      },
    });

    return NextResponse.json({
      success: true,
      project: {
        id: project.id,
        name: project.name,
        poapEventId: project.poapEventId,
        twitterHashtag: project.twitterHashtag,
        isActive: project.isActive,
        botAccount: project.botAccount,
        createdAt: project.createdAt.toISOString(),
      },
    });
  } catch (error) {
    console.error('Error creating project:', error);
    return NextResponse.json(
      {
        error: 'Failed to create project',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}
